INTEGER :: &
  & MPI_SUCCESS                                       , &
  & MPI_MAX                                           , &
  & MPI_MIN                                           , &
  & MPI_SUM                                           , &
  & MPI_BXOR                                          , &
  & MPI_CHARACTER                                     , &
  & MPI_INTEGER                                       , &
  & MPI_INTEGER8                                      , &
  & MPI_LOGICAL                                       , &
  & MPI_BYTE                                          , &
  & MPI_REAL8                                         , &
  & MPI_REAL4                                         , &
  & MPI_COMM_WORLD                                    , &
  & MPI_COMM_NULL                                     , &
  & MPI_STATUS_SIZE                                   , &
  & MPI_MAX_ERROR_STRING                              , &
  & MPI_TAG                                           , &
  & MPI_ANY_TAG                                       , &
  & MPI_SOURCE                                        , &
  & MPI_ANY_SOURCE                                    , &
  & MPI_UNDEFINED                                     , &
  & MPI_THREAD_MULTIPLE                               , &
  & MPI_THREAD_SINGLE                                 , &
  & MPI_MODE_RDONLY                                   , &
  & MPI_MODE_WRONLY                                   , &
  & MPI_MODE_CREATE                                   , &
  & MPI_INFO_NULL                                     , &
  & MPI_INTEGER4                                      , &
  & MPI_DOUBLE_PRECISION                              , &
  & MPI_2DOUBLE_PRECISION                             , &
  & MPI_MINLOC                                        , &
  & MPI_MAXLOC                                        , &
  & MPI_REQUEST_NULL                                  
COMMON / UMPICOM /  &
  & MPI_SUCCESS                                       , &
  & MPI_MAX                                           , &
  & MPI_MIN                                           , &
  & MPI_SUM                                           , &
  & MPI_BXOR                                          , &
  & MPI_CHARACTER                                     , &
  & MPI_INTEGER                                       , &
  & MPI_INTEGER8                                      , &
  & MPI_LOGICAL                                       , &
  & MPI_BYTE                                          , &
  & MPI_REAL8                                         , &
  & MPI_REAL4                                         , &
  & MPI_COMM_WORLD                                    , &
  & MPI_COMM_NULL                                     , &
  & MPI_STATUS_SIZE                                   , &
  & MPI_MAX_ERROR_STRING                              , &
  & MPI_TAG                                           , &
  & MPI_ANY_TAG                                       , &
  & MPI_SOURCE                                        , &
  & MPI_ANY_SOURCE                                    , &
  & MPI_UNDEFINED                                     , &
  & MPI_THREAD_MULTIPLE                               , &
  & MPI_THREAD_SINGLE                                 , &
  & MPI_MODE_RDONLY                                   , &
  & MPI_MODE_WRONLY                                   , &
  & MPI_MODE_CREATE                                   , &
  & MPI_INFO_NULL                                     , &
  & MPI_INTEGER4                                      , &
  & MPI_DOUBLE_PRECISION                              , &
  & MPI_2DOUBLE_PRECISION                             , &
  & MPI_MINLOC                                        , &
  & MPI_MAXLOC                                        , &
  & MPI_REQUEST_NULL                                  
REAL*8, EXTERNAL :: MPI_WTIME
