void mpi_abort_ () { umpi_die ("mpi_abort"); }
void mpi_allgather_ () { umpi_die ("mpi_allgather"); }
void mpi_allgatherv_ () { umpi_die ("mpi_allgatherv"); }
void mpi_allreduce_ () { umpi_die ("mpi_allreduce"); }
void mpi_alltoallv_ () { umpi_die ("mpi_alltoallv"); }
void mpi_barrier_ () { umpi_die ("mpi_barrier"); }
void mpi_bcast_ () { umpi_die ("mpi_bcast"); }
void mpi_bsend_ () { umpi_die ("mpi_bsend"); }
void mpi_buffer_attach_ () { umpi_die ("mpi_buffer_attach"); }
void mpi_buffer_detach_ () { umpi_die ("mpi_buffer_detach"); }
void mpi_cart_coords_ () { umpi_die ("mpi_cart_coords"); }
void mpi_cart_create_ () { umpi_die ("mpi_cart_create"); }
void mpi_cart_rank_ () { umpi_die ("mpi_cart_rank"); }
void mpi_cart_sub_ () { umpi_die ("mpi_cart_sub"); }
void mpi_comm_create_ () { umpi_die ("mpi_comm_create"); }
void mpi_comm_dup_ () { umpi_die ("mpi_comm_dup"); }
void mpi_comm_free_ () { umpi_die ("mpi_comm_free"); }
void mpi_comm_group_ () { umpi_die ("mpi_comm_group"); }
void mpi_comm_rank_ () { umpi_die ("mpi_comm_rank"); }
void mpi_comm_size_ () { umpi_die ("mpi_comm_size"); }
void mpi_comm_split_ () { umpi_die ("mpi_comm_split"); }
void mpi_error_string_ () { umpi_die ("mpi_error_string"); }
void mpi_file_close_ () { umpi_die ("mpi_file_close"); }
void mpi_file_iwrite_shared_ () { umpi_die ("mpi_file_iwrite_shared"); }
void mpi_file_write_ordered_ () { umpi_die ("mpi_file_write_ordered"); }
void mpi_file_write_ordered_begin_ () { umpi_die ("mpi_file_write_ordered_begin"); }
void mpi_file_write_ordered_end_ () { umpi_die ("mpi_file_write_ordered_end"); }
void mpi_file_write_shared_ () { umpi_die ("mpi_file_write_shared"); }
void mpi_finalize_ () { umpi_die ("mpi_finalize"); }
void mpi_finalized_ () { umpi_die ("mpi_finalized"); }
void mpi_gather_ () { umpi_die ("mpi_gather"); }
void mpi_gatherv_ () { umpi_die ("mpi_gatherv"); }
void mpi_get_count_ () { umpi_die ("mpi_get_count"); }
void mpi_group_free_ () { umpi_die ("mpi_group_free"); }
void mpi_group_incl_ () { umpi_die ("mpi_group_incl"); }
void mpi_iallgatherv_ () { umpi_die ("mpi_iallgatherv"); }
void mpi_ialltoallv_ () { umpi_die ("mpi_ialltoallv"); }
void mpi_ibcast_ () { umpi_die ("mpi_ibcast"); }
void mpi_ibsend_ () { umpi_die ("mpi_ibsend"); }
void mpi_igather_ () { umpi_die ("mpi_igather"); }
void mpi_igatherv_ () { umpi_die ("mpi_igatherv"); }
void mpi_init_ () { umpi_die ("mpi_init"); }
void mpi_initialized_ () { umpi_die ("mpi_initialized"); }
void mpi_init_thread_ () { umpi_die ("mpi_init_thread"); }
void mpi_iprobe_ () { umpi_die ("mpi_iprobe"); }
void mpi_irecv_ () { umpi_die ("mpi_irecv"); }
void mpi_iscatterv_ () { umpi_die ("mpi_iscatterv"); }
void mpi_isend_ () { umpi_die ("mpi_isend"); }
void mpi_probe_ () { umpi_die ("mpi_probe"); }
void mpi_recv_ () { umpi_die ("mpi_recv"); }
void mpi_scatter_ () { umpi_die ("mpi_scatter"); }
void mpi_scatterv_ () { umpi_die ("mpi_scatterv"); }
void mpi_send_ () { umpi_die ("mpi_send"); }
void mpi_ssend_ () { umpi_die ("mpi_ssend"); }
void mpi_testsome_ () { umpi_die ("mpi_testsome"); }
void mpi_type_size_ () { umpi_die ("mpi_type_size"); }
void mpi_wait_ () { umpi_die ("mpi_wait"); }
void mpi_waitall_ () { umpi_die ("mpi_waitall"); }
void mpi_waitany_ () { umpi_die ("mpi_waitany"); }
void mpi_waitsome_ () { umpi_die ("mpi_waitsome"); }
void mpi_wtime_ () { umpi_die ("mpi_wtime"); }
